default: &default
  pool: 1000
  adapter: postgresql
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  host: <%= ENV.fetch("DB_HOSTNAME") %>

development:
  <<: *default
  database: project_zp

test:
  <<: *default
  database: project_zp

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
